const historyOfLondonsParks = {'quizTitle': 'HistoryOfLondonParks', 'quizArray': [
{index: 1, 
    questionString: "What was the name of the first public park in London?", 
    questionType: "singleChoice",
    arrayOfAnswers: ["Battersea Park", "Finsbury Park", "Southwark Park", "Victoria Park"], 
    AnswerIndex: 3, 
    explanationToIncorrectAns: "London’s first public park, Victoria Park, was established in Hackney in 1842."}, 
{index: 2, 
    questionString: "The Wellington Arch, stands in Hyde Park. Built in 1825-27, what was the monuments original purpose?", 
    questionType: "singleChoice",
    arrayOfAnswers: ["To commemorate the Battle of Waterloo", "Intended as an outer entrance to Buckingham Palace", "A purpose-built viewing deck for Hyde Park visitors", "To demonstrate Charles Barry architecture"], 
    AnswerIndex: 1, 
    explanationToIncorrectAns: "Wellington Arch, one of London's best-known landmarks, was built in 1825–7 and was originally intended as an outer entrance to Buckingham Palace. "}, 
{index: 3, 
    questionString: "When was the Queen Elizabeth Olympic Park built?", 
    questionType: "singleChoice",
    arrayOfAnswers: ["1899", "2005", "2012", "2017"], 
    AnswerIndex: 2, 
    explanationToIncorrectAns: " It was purpose-built for the 2012 Summer Olympics and Paralympics, situated adjacent to the Stratford City development."}, 
{index: 4, 
    questionString: "There are 8 Royal Parks in London. Which park's are the Royal ones?", 
    questionType: "multChoice",
    arrayOfAnswers: ["Richmond Park", "Wimbledon Common", "Hyde Park", "Clapham Common", "Epping Forest", "Regent's Parks", "Dulwich Park", "Hampstead Heath"], 
    AnswerIndex: [0, 2, 5, 7], 
    explanationToIncorrectAns: "Richmond Park, Hyde Park, Regent's Parks and Hampstead Heath are all royal parks"},
{index: 5, 
    questionString: "Bunhill Fields is about 1.6 hectares in extent and the bulk of the site is a public garden. What was the formar park?", 
    questionType: "singleChoice",
    arrayOfAnswers: ["Burial ground", "Privte Garden", "Clay Pit", "Stables"], 
    AnswerIndex: 0, 
    explanationToIncorrectAns: "Bunhill fields Burial Ground is a historically significant burial ground as well as a vital open space of ecological value in London Borough of Islington. The site has five enclosed areas containing over 2,300 memorials with a publicly accessible garden to the north including benches, planting and a lawn area."}, 
{index: 6, 
    questionString: "How much of London is covered by public open space?", 
    questionType: "singleChoice",
    arrayOfAnswers: ["1%", "6%", "18%", "27%"], 
    AnswerIndex: 2, 
    explanationToIncorrectAns: "With 3,000 parks of varying sizes designated by the boroughs as 'public open space', London is a green city."}, 
{index: 7, 
    questionString: "St James's Park is the oldest park in London. When was it Estabilished?", 
    questionType: "singleChoice",
    arrayOfAnswers: ["1603", "1768", "1860", "1900"], 
    AnswerIndex: 0, 
    explanationToIncorrectAns: "On James I's accession to the throne in 1603, he ordered that the park be drained and landscaped, and exotic animals were kept in the park, including camels, crocodiles, an elephant and exotic birds, kept in aviaries."}, 
{index: 8, 
    questionString: "PostMans Park displays George Frederick Watts Memorial. What acts does the memorial celebrating?", 
    questionType: "singleChoice",
    arrayOfAnswers: ["Great Leaders", "Industrial Achievements", "Heroic self-sacrifice", "Long Standing Public Servants"], 
    AnswerIndex: 2, 
    explanationToIncorrectAns: "George Frederick Watts Memorial remembered long ago acts of heroic self sacrifice by ordinary men, women and children."}, 
{index: 9, 
    questionString: "True or False, London has the most green space than any other city in the United Kingdom?", 
    questionType: "singleChoice",
    arrayOfAnswers: ["True", "False"], 
    AnswerIndex: 1, 
    explanationToIncorrectAns: "Edinburgh has the largest ratio of green space to built environment of any UK city, with natural areas accounting for a whopping 49.2% of the city. London for comparison is about 18%"}, 
{index: 10, 
    questionString: "Soho Square, which dates back to 1681, stands a half-timbered gardener’s hut. What is underneath it?", 
    questionType: "singleChoice",
    arrayOfAnswers: ["Well", "Substation", "Grave", "Mediaeval ruins"], 
    AnswerIndex: 1, 
    explanationToIncorrectAns: "The hut was built in 1925 as an access point to the electricity substation beneath it."}, 
{index: 11, 
    questionString: "What is the most common tree found in London's parks?", 
    questionType: "singleChoice",
    arrayOfAnswers: ["English Oak", "London plane", "Silver Birch", "Sweet Chestnut"], 
    AnswerIndex: 1, 
    explanationToIncorrectAns: "London plane or (Platanus x hispanica) was widely planted as a street tree during the eighteenth and nineteenth centuries, inspired by the Parisian trend of lining streets with leafy trees."}, 
{index: 12, 
    questionString: "Richmond Park is famous for it's pastoral landscape of hills, woodlands, ponds, gardens and grasslands set amongst ancient trees. What are the animals that roam freely in the park?", 
    questionType: "singleChoice",
    arrayOfAnswers: ["Deer", "Sheep", "Cows", "Horses"], 
    AnswerIndex: 0, 
    explanationToIncorrectAns: "Richmond Park is a National Nature Reserve and deer park with 630 Red and Fallow deer roaming freely since 1637."}
    ]}