const storedAnswersAndQuestions = [{index: 1, 
    questionFireOfLondon: "What year did the greate fire of London start?", 
    arrayOfAnswers: ["1567", "1665", "1666", "1731"], 
    AnswerIndex: 2, 
    explanationToIncorrectAns: 'The Great Fire of London was a major conflagration that swept through central London from Sunday 2 September to Thursday 6 September 1666, gutting the medieval City of London inside the old Roman city wall, while also extending past the wall to the west'}, 
{index: 2, 
    questionFireOfLondon: "How many rivers run through london", 
    arrayOfAnswers: ["10", "26", "32", "56"], 
    AnswerIndex: 1, 
    explanationToIncorrectAns: 'There are 26 main rivers in London. This includes the River Thames, plus 25 tributaries which flow into the Thames.'}, 
{index: 3, 
    questionFireOfLondon: "Which of Londons public museums is the oldest?", 
    arrayOfAnswers: ["The British Museum", "Vicroria and Albert Museum", "Natural Histoty Museum", "Sir John Soane's Museum"], 
    AnswerIndex: 0, 
    explanationToIncorrectAns: "The British Museum is the world's oldest national public museum. Founded in 1753, it opened its doors in 1759, 17 years before the Declaration of Independence. It was free to all 'studious and curious persons', and it's still free today"}, 
{index: 4, 
    questionFireOfLondon: "London has the oldest underground railway, also knowen as the Tube. But what was the first tube Line?", arrayOfAnswers: ["District line", "Metroplitan Line", "Central Line", "Victoria Line"], 
    AnswerIndex: 1, 
    explanationToIncorrectAns: 'Opened in 1863, The Metropolitan Railway between Paddington and Farringdon was the first, urban, underground railway in the world.'}, 
{index: 5, 
    questionFireOfLondon: "How many times has London held the Olympics?", 
    arrayOfAnswers: ["1", "2", "3", "4"], 
    AnswerIndex: 2, 
    explanationToIncorrectAns: "United Kingdom has hosted the Olympic Games three times, in London in 1908 and 1948, and again in 2012."}, 
{index: 6, 
    questionFireOfLondon: "St. Paul's Cathedral is an icon of London, when was it built between?", 
    arrayOfAnswers: ["1645-1678", "1675-1701", "1715-1720", "1777-1799"], 
    AnswerIndex: 1, 
    explanationToIncorrectAns: "Designed and built (1675–1710) under the supervision of Sir Christopher Wren, it combines Neoclassical, Gothic, and Baroque elements."}, 
{index: 7, 
    questionFireOfLondon: "The Thames Barrier was completed in the 1980s, but for what purpose?", 
    arrayOfAnswers: ["To protect the city from Tidal Floods", "To Supply freshwater to Londoners", "To stop big boats from heading up the river", "To reduce the speed of the river flow"], 
    AnswerIndex: 0, 
    explanationToIncorrectAns: 'Protects 125 square kilometres of central London from flooding caused by tidal surges.'}, 
{index: 8, 
    questionFireOfLondon: "Until the 1980s, Fish and Chips were served in?", 
    arrayOfAnswers: ["Boxes", "Newspaper", "Plates", "Cups"], 
    AnswerIndex: 1, 
    explanationToIncorrectAns: 'The use of old newspapers as wrapping paper was mainly for keeping warm and soaking up the fat.'}, 
{index: 9, 
    questionFireOfLondon: "How many Tube stations are there in operation?", 
    arrayOfAnswers: ["60", "135", "272", "370"], 
    AnswerIndex: 2, 
    explanationToIncorrectAns: 'London Underground, better known as the Tube, has 11 lines covering 402km and serving 272 stations.'}, 
{index: 10, 
    questionFireOfLondon: "London has a lot of trees, so many infact that the United Nations has classified London as an forest. Do you know how many trees are in London?", 
    arrayOfAnswers: ["1 million", "2 million", "4 million", "8 million"], 
    AnswerIndex: 3, 
    explanationToIncorrectAns: "London's urban forest contains an estimated 8 million trees and covers around 21 per cent of the city's land area."}, 
{index: 11, 
    questionFireOfLondon: "When Hitler invaded Europe, several displaced governments moved to London, which where they?", 
    arrayOfAnswers: ["Poland, Norway, France and Holland", "Poland, Norway, Belgium, France and Holland", "Poland, Norway, Spain, Belgium, France and Holland", "Poland, Denmark, Italy, France and Holland"], 
    AnswerIndex: 1, 
    explanationToIncorrectAns: 'Poland, Norway, Belgium, France and Holland/Netherlands'}, 
{index: 12, 
    questionFireOfLondon: "When did the Romans found London or Londinium?", 
    arrayOfAnswers: ["10 BC", "47 AD", "120 AD", "320 AD"], 
    AnswerIndex: 1, 
    explanationToIncorrectAns: 'Ancient Romans founded a port and trading settlement called Londinium in 43 A.D.'}]
